### ISSUE TITLE
module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by summerrain1234** [dreamer2908/Python-CRC32-Hasher#3]
line 641, in initStuff
    defaultTimer = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by dreamer2908** [comment]
Fixed in https://github.com/dreamer2908/Python-CRC32-Hasher/commit/6146cb4bb5ff04fe13b2f366c40f7fe9ec027caa
time.clock() was replaced with time.perf_counter() since Python 3.8. 
I didn't notice it because I've only used up to Python 3.7 so far.
